[package]
name = "client"
version = "0.1.0"
edition = "2021"


[dependencies]
concrete = { version = "0.2.0-beta", features = ["serde", "shortints", "integers"] }
commons = { path = "../commons" }
serde = "1.0.138"
byteorder = "1.4.3"
bincode = "1.3.3"
colored = "2.0.0"



