[package]
name = "commons"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = { version = "1.0.138", features = ["derive"] }
concrete = { version = "0.2.0-beta", features = ["serde", "shortints", "integers"] }
